version: "3.9"
services:
  malwaretotal:
    image: "explabs/malwaretotal:latest"
#   or  build: .
    ports:
      - "8000:8000"
    volumes:
      - malware.json:/app

#   That is a docker-compose file example